#hibernate.dialect=org.raven.hibernate.dialect.MySQLDialect
#hibernate.globally_quoted_identifiers=true
#hibernate.persister.resolver=org.raven.hibernate.persister.DefinePersisterClassResolver
#hibernate.session_factory.statement_inspector=org.raven.hibernate.interceptor.SqlStatementInterceptor

hibernate.type.json_format_mapper=org.raven.hibernate.type.JacksonJsonFormatMapper