<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.raven-source</groupId>
        <artifactId>raven-framework</artifactId>
        <version>5.0.2</version>
    </parent>

    <artifactId>raven-hibernate</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>raven-hibernate-jpa-test</module>
        <module>raven-hibernate-commons</module>
        <module>raven-hibernate-jpa</module>
        <module>raven-hibernate-jpa-starter</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <encoding>UTF-8</encoding>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>

        <spring-data-bom.version>2025.0.3</spring-data-bom.version>
        <spring-data-jpa.version>3.5.3</spring-data-jpa.version>

        <hibernate.version>6.6.13.Final</hibernate.version>
        <hibernate.common.version>7.0.3.Final</hibernate.common.version>
<!--        <hypersistence-utils-hibernate-63.version>3.7.7</hypersistence-utils-hibernate-63.version>-->
<!--        <hibernate-types-52.version>2.14.1</hibernate-types-52.version>-->
        <mysql-connector.version>9.2.0</mysql-connector.version>
        <clickhouse-jdbc.version>0.8.6</clickhouse-jdbc.version>
        <HikariCP.version>5.1.0</HikariCP.version>

        <checker-qual.version>3.49.5</checker-qual.version>
        <antlr4-runtime.version>4.13.2</antlr4-runtime.version>
        <jakarta.validation.version>3.0.2</jakarta.validation.version>
        <raven-framework.version>5.0.2</raven-framework.version>

        <raven-hibernate.version>${project.version}</raven-hibernate.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>io.github.raven-source</groupId>
            <artifactId>raven-commons</artifactId>
            <version>${raven-framework.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-simple</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!--<dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>annotations</artifactId>
            <version>3.0.1</version>
        </dependency>-->

        <dependency>
            <groupId>com.github.spotbugs</groupId>
            <artifactId>spotbugs-annotations</artifactId>
            <version>${spotbugs-annotations.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.checkerframework</groupId>
            <artifactId>checker-qual</artifactId>
            <version>${checker-qual.version}</version>
            <scope>provided</scope>
        </dependency>

    </dependencies>

    <name>${project.groupId}:${project.artifactId}</name>
    <description>Raven Mongodb Library</description>
    <url>https://raven-source.github.io/</url>

    <scm>
        <url>https://github.com/Raven-Source/raven-hibernate</url>
        <connection>scm:git:https://github.com/Raven-Source/raven-hibernate.git</connection>
        <developerConnection>scm:git:https://github.com/Raven-Source/raven-hibernate.git</developerConnection>
        <tag>HEAD</tag>
    </scm>

    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>yi.liang</name>
            <email>indifer@126.com</email>
            <organization>raven</organization>
            <organizationUrl>https://github.com/Raven-Source</organizationUrl>
        </developer>
    </developers>

    <dependencyManagement>

        <dependencies>

            <!--<dependency>
                <groupId>com.vladmihalcea</groupId>
                <artifactId>hibernate-types-52</artifactId>
                <version>${hibernate-types-52.version}</version>
            </dependency>-->

            <dependency>
                <groupId>org.hibernate.orm</groupId>
                <artifactId>hibernate-core</artifactId>
                <version>${hibernate.version}</version>
            </dependency>

            <dependency>
                <groupId>org.hibernate.common</groupId>
                <artifactId>hibernate-commons-annotations</artifactId>
                <version>${hibernate.common.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-bom</artifactId>
                <version>${spring-data-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-jpa</artifactId>
                <version>${spring-data-jpa.version}</version>
            </dependency>

            <dependency>
                <groupId>org.antlr</groupId>
                <artifactId>antlr4-runtime</artifactId>
                <version>${antlr4-runtime.version}</version>
            </dependency>

            <dependency>
                <groupId>jakarta.validation</groupId>
                <artifactId>jakarta.validation-api</artifactId>
                <version>${jakarta.validation.version}</version>
            </dependency>

            <dependency>
                <groupId>jakarta.persistence</groupId>
                <artifactId>jakarta.persistence-api</artifactId>
                <version>3.1.0</version>
            </dependency>

            <!--<dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>2.0.17</version>
            </dependency>-->

        </dependencies>

    </dependencyManagement>

    <profiles>

        <profile>
            <id>deploy-central</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <modules>
                <module>raven-hibernate-commons</module>
                <module>raven-hibernate-jpa</module>
                <module>raven-hibernate-jpa-starter</module>
            </modules>

            <distributionManagement>
                <snapshotRepository>
                    <id>oss</id>
                    <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
                </snapshotRepository>
                <repository>
                    <id>oss</id>
                    <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
                </repository>
            </distributionManagement>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>0.8.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>central</publishingServerId>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- mvn versions:set -DprocessAllModules=true -DnewVersion=1.x-SNAPSHOT -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.7</version>
                <configuration>
                    <generateBackupPoms>false</generateBackupPoms>
                </configuration>
            </plugin>

        </plugins>

    </build>

</project>