package org.raven.hibernate.jpa.test.config;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

public class ClickHouseConnectionWrapper implements Connection {
    private final Connection delegate;

    public ClickHouseConnectionWrapper(Connection delegate) {
        this.delegate = delegate;
    }

    // --- 拦截事务相关操作 ---
    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        if (!autoCommit) {
            // ClickHouse 不支持关闭 auto-commit，忽略
            return;
        }
        delegate.setAutoCommit(true);
    }

    @Override
    public boolean getAutoCommit() throws SQLException {
        return true; // 始终 true
    }

    @Override
    public void commit() throws SQLException {
        // ClickHouse 不支持事务提交，忽略
    }

    @Override
    public void rollback() throws SQLException {
        // ClickHouse 不支持事务回滚，忽略
    }

    @Override
    public Savepoint setSavepoint() throws SQLException { return null; }
    @Override
    public Savepoint setSavepoint(String name) throws SQLException { return null; }
    @Override
    public void rollback(Savepoint savepoint) throws SQLException { }
    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException { }

    @Override
    public void setTransactionIsolation(int level) throws SQLException { }
    @Override
    public int getTransactionIsolation() throws SQLException { return Connection.TRANSACTION_NONE; }

    // --- 其他方法直接委托 ---
    @Override
    public Statement createStatement() throws SQLException { return delegate.createStatement(); }
    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return delegate.createStatement(resultSetType, resultSetConcurrency);
    }
    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return delegate.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException { return delegate.prepareStatement(sql); }
    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return delegate.prepareStatement(sql, autoGeneratedKeys);
    }
    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return delegate.prepareStatement(sql, columnIndexes);
    }
    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return delegate.prepareStatement(sql, columnNames);
    }
    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return delegate.prepareStatement(sql, resultSetType, resultSetConcurrency);
    }
    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException { return delegate.prepareCall(sql); }
    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return delegate.prepareCall(sql, resultSetType, resultSetConcurrency);
    }
    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return delegate.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override
    public String nativeSQL(String sql) throws SQLException { return delegate.nativeSQL(sql); }
    @Override
    public void close() throws SQLException { delegate.close(); }
    @Override
    public boolean isClosed() throws SQLException { return delegate.isClosed(); }
    @Override
    public DatabaseMetaData getMetaData() throws SQLException { return delegate.getMetaData(); }
    @Override
    public void setReadOnly(boolean readOnly) throws SQLException { delegate.setReadOnly(readOnly); }
    @Override
    public boolean isReadOnly() throws SQLException { return delegate.isReadOnly(); }
    @Override
    public void setCatalog(String catalog) throws SQLException { delegate.setCatalog(catalog); }
    @Override
    public String getCatalog() throws SQLException { return delegate.getCatalog(); }
    @Override
    public SQLWarning getWarnings() throws SQLException { return delegate.getWarnings(); }
    @Override
    public void clearWarnings() throws SQLException { delegate.clearWarnings(); }
    @Override
    public Map<String, Class<?>> getTypeMap() throws SQLException { return delegate.getTypeMap(); }
    @Override
    public void setTypeMap(Map<String, Class<?>> map) throws SQLException { delegate.setTypeMap(map); }
    @Override
    public void setHoldability(int holdability) throws SQLException { delegate.setHoldability(holdability); }
    @Override
    public int getHoldability() throws SQLException { return delegate.getHoldability(); }
    @Override
    public Clob createClob() throws SQLException { return delegate.createClob(); }
    @Override
    public Blob createBlob() throws SQLException { return delegate.createBlob(); }
    @Override
    public NClob createNClob() throws SQLException { return delegate.createNClob(); }
    @Override
    public SQLXML createSQLXML() throws SQLException { return delegate.createSQLXML(); }
    @Override
    public boolean isValid(int timeout) throws SQLException { return delegate.isValid(timeout); }
    @Override
    public void setClientInfo(String name, String value) throws SQLClientInfoException { delegate.setClientInfo(name, value); }
    @Override
    public void setClientInfo(Properties properties) throws SQLClientInfoException { delegate.setClientInfo(properties); }
    @Override
    public String getClientInfo(String name) throws SQLException { return delegate.getClientInfo(name); }
    @Override
    public Properties getClientInfo() throws SQLException { return delegate.getClientInfo(); }
    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException { return delegate.createArrayOf(typeName, elements); }
    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException { return delegate.createStruct(typeName, attributes); }
    @Override
    public void setSchema(String schema) throws SQLException { delegate.setSchema(schema); }
    @Override
    public String getSchema() throws SQLException { return delegate.getSchema(); }
    @Override
    public void abort(Executor executor) throws SQLException { delegate.abort(executor); }
    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException { delegate.setNetworkTimeout(executor, milliseconds); }
    @Override
    public int getNetworkTimeout() throws SQLException { return delegate.getNetworkTimeout(); }
    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException { return delegate.unwrap(iface); }
    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException { return delegate.isWrapperFor(iface); }
}